title: Bond Keevil's Software Development Blog
email: me@bondkeevil.ca
timezone: America/Toronto
description: Bond Keevil's software development blog
github_username:  bkeevil
markdown: kramdown
theme: jekyll-theme-hacker
