title: Bond Keevil
email: me@bondkeevil.ca
description: >- # this means to ignore newlines until "baseurl:"
  I'm a part time programmer/analyst that lives in a remote part of Ontario, 
  Canada and the libertarian provincial candidate for the Nipissing
  district. I used to run an ISP in Vancouver BC and had a small business
  fixing computers for many years. This is an economically dead town with
  no local IT economy so I mostly do open source stuff to keep me busy.
  I'm always interested in opportunities for both paid projects and volunteer 
  projects that are for a good cause.
  This site has news and updates about my recent software development activities and a list of 
  my repositories.
github_username:  bkeevil

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
