title: justsomehacker@bondkeevil.ca
email: me@bondkeevil.ca
description: >- # this means to ignore newlines until "baseurl:"
  I'm just some hacker that lives in a remote part of Ontario, 
  Canada. No local economy IT economy to speak of here so I mostly
  do open source stuff to keep me busy. This site has news and 
  updates about my software development activities and a list of 
  my repositories.
github_username:  bkeevil

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
